### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by chrissexton** [IUS-CS/c346-34515-fa22-project-funnygroupname#16]
Most of this is fine, but I'm a bit confused about a few things (please reply for clarity).

## Goals?

Is this a fake website for a fake business? What is this $50,000? Do you store data? What data and why? None of this makes any sense to me. This should not be a fantasy project, but something that has realistic merit. That _could_ be a scheduling system for a Dentistry, but there's no need to BS some imaginary practice. [edit:] It would be fine to call it a product to sell to dentistries as a web solution for their practice. Label it that way unless you have a real single-client.

### Makefile

What is this makefile for? It looks to me like you have two javascript projects for front and backend, but the makefile specifies nonexistent C++ code. It makes plenty of sense to alias the `npm` commands in a makefile, but I'm left confused what that file is doing right now. If it's doing nothing, it should be removed.

### Mongo

You state that you have a database backend, and that's fine. What's it for? From what I see in the proposal, you just intend to have informational pages. What are you storing in a dynamic database? What's its purpose?

To be clear: I want there to be a purpose. An informational set of webpages is not anywhere near enough for this project. You should have a dynamic program that does something useful, not something that just displays information that could just as well be a couple of .html files.

## Testing

You should have test frameworks setup for both front and backend. See that you do that this sprint.

**Comment by chrissexton** [comment]
Still waiting on that reply.

**Comment by mccoyJosh** [comment]
Goals?
Our original idea was to make a website for a fake company, but we are going to head in the direction of what you proposed: a web solution for dental services (we are updating the proposal to match that immediately). We will remove the budget provided and more clearly explain the services of the web solution. 

Makefile
Josh had originally put that in with the intent of utilizing the format of the Makefile to use for our project. The Makefile originally came from a previous project that used C++. This should not have been added until it was actually pertinent to our project, BUT that is the case now. The Makefile runs the necessary code to get the dependencies the website needs to run.

MongoDB
A more robust explanation of the purpose of the MongoDB database will be in the proposal. It really was not clear, but we are going to fix that.

Testing FrameWork
GOT IT. Will do.
